[env:m5stickc-plus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
lib_deps =
  m5stack/M5StickCPlus2
  h2zero/NimBLE-Arduino@^1.4.3
lib_ignore =
  DFRobot_GP8XXX
build_flags =
  -DCORE_DEBUG_LEVEL=1
